/waypoints/1/x: 0.0
/waypoints/1/y: 0.0
/waypoints/1/theta: 0
/waypoints/2/x: 2.0
/waypoints/2/y: 3.0
/waypoints/2/theta: 11.309932474
/waypoints/3/x: 4.0
/waypoints/3/y: 5.0
/waypoints/3/theta: 173.659808254
/waypoints/4/x: 0.0
/waypoints/4/y: 0.0
/waypoints/4/theta: 0
