/waypoints/1/x: -19.0
/waypoints/1/y: 0.0
/waypoints/1/theta: 0
/waypoints/2/x: -19.0
/waypoints/2/y: 8.0
/waypoints/2/theta: 3.08609414834
/waypoints/3/x: 2.0
/waypoints/3/y: -3.0
/waypoints/3/theta: 3.08609414834
/waypoints/4/x: -2.0
/waypoints/4/y: -3.0
/waypoints/4/theta: 3.08609414834
/waypoints/5/x: -2.0
/waypoints/5/y: 3.0
/waypoints/5/theta: 3.08609414834


